### ISSUE TITLE
Clarifying our rate limit enforcement

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/roadmap#11]
@cschneid handled an issue via Slack where a customer was confused about when the rate limit for viewing transaction traces is reset.

Wanted to clarify how I believe this works.

`app/views/slow/_tree` initializers a `PlanEnforcer` using the time of the trace:

```
- plan_enforcer = @plan_enforcer || PlanEnforcer.new(current_org, time: @trace.time)
```

`PlanEnforcer` looks for a `PlanEnforcementEvent` that occurs within a 24-hour period of the time of the day of the trace. Example raw SQL:

```
SELECT  "plan_enforcement_events".* FROM "plan_enforcement_events" WHERE "plan_enforcement_events"."org_id" = $1 AND (time >= date_trunc('day', timestamp '2017-08-24 17:03:56.000000')
       AND time < (date_trunc('day', timestamp '2017-08-24 17:03:56.000000') + interval '1 day')) AND "plan_enforcement_events"."plan" = $2 AND "plan_enforcement_events"."label" = $3  ORDER BY "plan_enforcement_events"."id" ASC LIMIT 1  [["org_id", 3433], ["plan", "chair"], ["label", "transactions"]]
```

The timezone of the user doesn't matter.

## The Problem

These traces are not viewable again as long as the plan is not upgraded. I think this user expected them to be viewable after the rate limit resets. Since we're passing thru the time of the trace when initializing a `PlanEnforcer`, no conditions change.

Our language is consistent with this:

```
The 24-hour transaction rate limit was
        |&nbsp;exceeded. To view this trace, upgrade your plan.
```

When the plan is upgraded, the trace will be viewable (we search for `plan_enforcement_events` that match the given plan.

## Biz Question

If prior traces are viewable after resetting the rate limit, users will likely just deal with it. Our current logic basically forces an upgrade. I've fine w/that approach.

**Comment by cschneid** [comment]
Ah - you never reset for the day you went over your limit on? That's what I
was confused about.

To clarify, is this right?

```
Monday - fine
Tuesday - go over limit
Wednesday - fine
```

You'll never be able to see tuesday's traces without upgrading. Does it
block all traces on Tuesday, or just ones after that limit tripped on that
day?
