### ISSUE TITLE
Add webhook notification channel

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/roadmap#19]
See:

https://docs.bugsnag.com/product/integrations/webhook/
https://airbrake.io/docs/integrations/webhooks/
https://rollbar.com/docs/webhooks/

**Comment by trevordmiller** [comment]
This would be great! Just generic JSON events to any service - not one in particular - like other tools do:
https://docs.bugsnag.com/product/integrations/webhook/
https://airbrake.io/docs/integrations/webhooks/
https://rollbar.com/docs/webhooks/

**Comment by garrettqmartin8** [comment]
We would love this!

**Comment by dlanderson** [comment]
We've released WebHook notification channels recently: https://github.com/scoutapp/apm/pull/1350
