### ISSUE TITLE
Add column sorting to the list of apps

### ISSUE THREAD

**Issue by alzuin** [scoutapp/roadmap#22]
Please, add the possibility to change the order of the applications list in the home page.
For someone who has a big number of different applications monitored, could be sweet to order it by response time or throughput.
Thanks,
Alberto

**Comment by itsderek23** [comment]
Makes sense. FYI, the default ordering today is time consumed, which is the throughput * response time. This gives heavier weight to apps doing more work.

**Comment by itsderek23** [comment]
The list of apps is now sortable!

![image](https://user-images.githubusercontent.com/7880/39496033-137ca458-4d5a-11e8-8e19-49b893da7a55.png)

The sort selection is persisted via a cookie as well.

/cc @alzuin @bakongo @mike-stewart

Next - wondering about the ability to filter apps by name on this page and via the apps pulldown:

![image](https://user-images.githubusercontent.com/7880/39496686-c63ca514-4d5c-11e8-9180-442860685ac3.png)
