### ISSUE TITLE
NodeJS Support

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/roadmap#23]
Add the ability to monitor NodeJS apps, starting with Express.

**Comment by dlanderson** [comment]
Update: Node support is now in development!

**Comment by ramigluzman** [comment]
Any updates on this issue? I'd love to see it happening ❤️

**Comment by AgentShir** [comment]
Update: Our NodeJS agent is now in beta! Installation instructions can be [found in our Help Docs.](https://docs.scoutapm.com/#nodejs-agent). 

Currently, we support Express, version 4.x+ and instrument the following libraries out of the box:

- Postgres (via pg)
- MySQL (via mysql and mysql2)
- Pug
- Mustache
- EJS

Please contact support@scoutapm.com if you have any questions!
