### ISSUE TITLE
Bitbucket and Bugsnag Integration

### ISSUE THREAD

**Issue by renews** [scoutapp/roadmap#29]
As the title says.

**Comment by itsderek23** [comment]
Thanks @renews.

I've added a dedicated issue for Bugsnag - see #30.

#18 is for Bitbucket. Mind following those? Going to mark this as a duplicate and close.

**Comment by renews** [comment]
Sure, sorry for the duplicate.

**Comment by itsderek23** [comment]
No problems - thx for contributing!
