### ISSUE TITLE
Support Self-Hosted Sentry Installs

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/roadmap#31]
Our error integration supports Sentry.io, but not self-hosted installs. 

Add support for self-hosted installs by allowing the customer to ender a different BASE URL.

**Comment by danbt79** [comment]
👍 Yes please - this would be good.

**Comment by austra** [comment]
Looking forward to this.  Thank you!

**Comment by gabpaladino** [comment]
I will see it soon? 🙏

**Comment by fred** [comment]
Please! 
This would be great to have. 
Plus self hosted Github Enterprise support.

**Comment by seth-macpherson** [comment]
Yes!  Oh yes, please!  This would make a significant difference to my team.

**Comment by nyanev** [comment]
This would be great!

**Comment by dlanderson** [comment]
As of Nevember 2018, we now support Self Hosted Sentry installs
