### ISSUE TITLE
Add Scoutprof support for Background Jobs

### ISSUE THREAD

**Issue by cschneid** [scoutapp/roadmap#36]
A few tasks around this general request:

* [ ] Enable trace capturing in Jobs
* [ ] Add support in Ingest and UI of APM to display captured traces
* [ ] Test in heavily threaded environments like Sidekiq

**Comment by dlanderson** [comment]
We're testing [AutoInstruments](https://github.com/scoutapp/scout_apm_ruby/pull/247) which will replace ScoutProf. We plan on supporting BackGround jobs with AutoInstruments and it will not require the same changes as ScoutProf.
