### ISSUE TITLE
Node CPU usage, and Apdex isn't updated when a zoom timeframe is applied

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/roadmap#55]
@zdrummond reports two issues when applying a zoom timeframe:

* Node CPU usage % doesn't appear to change
* Apdex - goes to zero

**Comment by zdrummond** [comment]
And using Firefox 59.0.2 (64-bit), if I try to click the drop-down for the timeframe's endpoint list, the list dismisses. This doesn't happen on Chrome.

**Comment by itsderek23** [comment]
> Node CPU usage % doesn't appear to change
Apdex - goes to zero

I haven't been able to reproduce this.

When I change the timeframe (either a longer timeframe, like 3 hours, or to a prior day):

![image](https://user-images.githubusercontent.com/7880/39498634-7230506a-4d66-11e8-80d7-0504d982ccf3.png)

The node metrics at the bottom of the page:

![image](https://user-images.githubusercontent.com/7880/39498641-81834248-4d66-11e8-8c6c-72e18ddd31e2.png)

...do change. Same with Apdex.

To confirm, these are NOT changing for you @zdrummond ?

**Comment by zdrummond** [comment]
The timeframe control works.

The highlight a time window in that time frame does not.

________________________________

**Comment by itsderek23** [comment]
Ah yes - I'm able to reproduce. Thanks @zdrummond!

![image](https://user-images.githubusercontent.com/7880/39498826-b12f1f02-4d67-11e8-89ba-4f420527021d.png)

> And using Firefox 59.0.2 (64-bit), if I try to click the drop-down for the timeframe's endpoint list, the list dismisses. This doesn't happen on Chrome.

Reproduced:

![image](https://user-images.githubusercontent.com/7880/39498898-2e3b499e-4d68-11e8-83e6-91ae21a44533.png)

**Comment by itsderek23** [comment]
> And using Firefox 59.0.2 (64-bit), if I try to click the drop-down for the timeframe's endpoint list, the list dismisses. This doesn't happen on Chrome.

I turned this into a separate issue - #57 - as it is an unrelated bug.

**Comment by itsderek23** [comment]
> Node CPU usage % doesn't appear to change

This will now change, but it does require a page refresh as we aren't yet updating the page as part of the zoom interaction. We wanted to get this in place as the zoom interaction update is more involved. 

You can verify if the zoom timeframe is being used:

![image](https://user-images.githubusercontent.com/7880/39534780-9fe5a45e-4def-11e8-8b14-5f2b77d0a161.png)

> Apdex - goes to zero

Fixed.

Thanks for reporting @zdrummond!
