### ISSUE TITLE
Feature request: ability to configure the APDEX T value.

### ISSUE THREAD

**Issue by dogweather** [scoutapp/roadmap#61]
I set a pretty high bar for my apps: I want the server response time to be 200ms or faster. And so if I could, I'd use that 200ms value for the `T` in the APDEX calculation. (I've done this when I used New Relic.) I'm guessing, though, that the current APDEX formula has a hard-coded T value of something like 500ms. Because: my APDEX is always at 1.0, even as I work to make my app faster. :-)

**Comment by neilvcarvalho** [comment]
I also have this problem. With a `T` value so high, it's difficult to get the hot spots. I like this article from New Relic: https://blog.newrelic.com/product-news/how-to-choose-apdex-t/

**Comment by dogweather** [comment]
Yep! Since I wrote this Issue, I've raised my expectations for my sites: server response time of 100ms. So the hard-coded T at ~500ms is pretty irrelevant for me.

**Comment by filipiz** [comment]
Comenting to bring the attention to this.
Hability to configure Apdex T is important to me too.

**Comment by cschneid** [comment]
This feature is now implemented and deployed. You can find it in the application settings page.

**Comment by dogweather** [comment]
Awesome - thanks!
