### ISSUE TITLE
Smart render floats in charts

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/roadmap#63]
Currently, context with `Numeric` values are rendered using a log-scaled histogram.

For example, response time:

![image](https://user-images.githubusercontent.com/7880/39834080-1a8f2c54-5389-11e8-9d74-0f970cbab03b.png)

This display format doesn't work well if the numeric has a defined range (like an account id).

Investigate treating numerics like `String` values if there is a limited number of unique values.

**Comment by nathansamson** [comment]
Not sure if the fix would work. If you only have 20 or so requests, and they come from 10 different users. Would this count as limited unique values?

Could we do something based on the name? Eg if the name includes ID it is treated as with defined range, otherwise as histogram?

**Comment by itsderek23** [comment]
> If you only have 20 or so requests, and they come from 10 different users. Would this count as limited unique values?

What I'm thinking: if the data set contains more than 80% unique values, we treat as a `Numeric`.

So 10 unique users would still be treated as a `String` and render the row charts you are looking for.

We'd also combine this eventually with #53, so if some rows are hidden, you can still select those rows.

**Comment by itsderek23** [comment]
@nathansamson - try explorer again now and see if the data is rendered in a row chart.

**Comment by nathansamson** [comment]
Yep, old behaviour is back like I want :)

Thanks for the quick turn around

**Comment by itsderek23** [comment]
Great! Thanks for reporting.
