### ISSUE TITLE
Trace explorer limits number of traces

### ISSUE THREAD

**Issue by nathansamson** [scoutapp/roadmap#64]
Example
When I run traces for the past 12h the trace with the max duration is 27s.
When I run traces for the past 6h I get a trace with max duration 70s. (and it did happen a few hours ago, not like in the last minute)

It seems only 1000 traces are being used

What I would be able to do is check every day for the past 1 day, check ALL traces that are taking longer than a given threshold so I can optimize them. Now they are lost, if the first few traces of the day are quick...

I understand this is being done out of performance reasons

Possibe solutions:
* Let me prefilter on some variables (context) (eg response time) so I can filter intresting traces myself (eg slow ones, from a specific host, ...). I am happy to enter values myself, so no need to "loop" over all the traces to give me possible options
* Show a random sample (but this will give impredictable results. Reloading the page might give a different set)
* Show only the slowest traces. Which will solve my use case, but might give a wrong idea

**Comment by itsderek23** [comment]
What I'm thinking:

* Add a "Dataset" pulldown
* Contains 2 options to start:
  * Random (more representative)
  * Slowest

**Comment by itsderek23** [comment]
@nathansamson - released!

![image](https://user-images.githubusercontent.com/7880/41546778-c0862fb0-72db-11e8-82e7-cf028d3aee58.png)

The dataset option you select is maintained via a cookie so you don't have to toggle it every time.

**Comment by nathansamson** [comment]
I don't see this option?

![image](https://user-images.githubusercontent.com/93735/41600981-86f62a00-73d7-11e8-811c-acfff82c94a8.png)

**Comment by itsderek23** [comment]
> I don't see this option?

Apologies - try now.
