### ISSUE TITLE
Incorrect explanation on traces beyond retention period

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/roadmap#66]
If a user attempts to access a trace beyond our max retention period, we display the following:

![image](https://user-images.githubusercontent.com/7880/40316313-2d2256b0-5cdb-11e8-98eb-86a345b8650a.png)

This is incorrect. The message should remove the unlock / upgrade bits and say:

> This trace occurred beyond our retention limit.

**Comment by matthewchigira** [comment]
"This trace occurred more than 168 hours ago, which exceeds the time limit for your plan."

**Comment by AgentShir** [comment]
Just to clarify, our data retention policy is:

>30 days of metrics and 7 days of transaction traces

This is Scout's policy at the moment and it's the same across all of our plans.
