### ISSUE TITLE
Fix upgrade message w/db addon to account for 3.*.pre

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/roadmap#69]
Currently our `upgrade_agent.html.slim` page displays the following message if an app is using an agent that does not support the db addon:

```
Database Monitoring requires <code>scout_apm</code> version 2.3.0 or greater:
```

If an app is using the `3.*.pre` line of the Ruby agent, this is misleading. Instead, we should detect if this is the case and provide the proper Gem version for that line of the agent (`Gem::Version.new("3.0.0.pre12")`).

**Comment by dlanderson** [comment]
3.x.pre releases are being replaced with [AutoInstruments](https://github.com/scoutapp/scout_apm_ruby/pull/247)
