### ISSUE TITLE
Add Shoryuken instrumentation

### ISSUE THREAD

**Issue by vbalazs** [scoutapp/roadmap#72]
Many projects are running on AWS and using [shoryuken](https://github.com/phstc/shoryuken) as job processor instead of sidekiq.

It would be nice to see in the supported list.

**Comment by itsderek23** [comment]
Thanks @vbalazs - mind subscribing to this issue: https://github.com/scoutapp/scout_apm_ruby/issues/195

Going to mark as a duplicate.
