### ISSUE TITLE
Filtering data by user-defined context

### ISSUE THREAD

**Issue by trevvvy** [scoutapp/roadmap#74]
We would love the ability to provide some context to scout in our config, and then filter by that context.

The slices of the data that we would want to filter by are things that we would have to define, such as:
• region (which group of servers)
• role (what role is the server playing: application, versus media, versus reporting)
• customer_type (standard, enterprise, etc)

The main problem we're having is that our app is deployed to multiple AWS regions, for customers in each country. Problems in our smaller regions are hidden because the overall volume is lower in those regions.

We provide all this context to our datadog reporting, and it's really helpful for isolating performance problems.

**Comment by itsderek23** [comment]
@trevvvy - thanks for the suggestion. 

Have you tried adding [Scout context](http://help.apm.scoutapp.com/#ruby-custom-context) and using the [Trace Explorer](http://help.apm.scoutapp.com/#trace-explorer)?

**Comment by trevvvy** [comment]
ha! seems you've built the very thing I was imagining.  Do you plan to incorporate the filtering by context in the other sections of Scout?  Like the overview?

**Comment by trevvvy** [comment]
Gonna close this as it's well underway in #33
