### ISSUE TITLE
Database Monitoring

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/roadmap#8]
___[Complete this form](https://goo.gl/forms/QTzynP2sxC50w3zz1) for early access to database monitoring.___

---

Databases are a common controllable bottleneck for many applications. Poor query performance can cascade into impacting much of an application.

This is an attempt to provide a database-centric view of an app's health within Scout. 

Click the image below for a full-size screenshot:

![database_ui](https://user-images.githubusercontent.com/7880/29223918-756b9a06-7e85-11e7-973d-b2935d3f47aa.png)

## The fundamentals

* Track the ongoing performance of queries and their callers (which controller-actions and background jobs are triggering the queries). 
* Provide high-level metrics on overall db performance (query times and throughput)
* Support the following databases:
  * Postgres
  * MySQL
  * Redis
  * MongoDB

## The special sauce

It's easy to unintentionally commit a change to application code that harms db performance. Constantly analyze DB performance for events like the following:

* A new expensive query appears
* A query is frequently slow
* An N+1 is introduced
* A query is a bottleneck for a high-volume endpoint

These should connect directly to the source code location and the developers behind them so it's easy to identify someone to fix a problem.

## Early Access

[__Complete this form__](https://goo.gl/forms/QTzynP2sxC50w3zz1) for early access to database monitoring.

**Comment by sixfeetover** [comment]
This looks awesome. I'd love to see support for [SQL Server](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter) (direct db adapter: https://github.com/rails-sqlserver/tiny_tds) as well! Any chance of adding that, or providing instructions on how to add a new database for PR purposes?

**Comment by schneems** [comment]
When showing slow queries it would be helpful to show an example of what inputs that query takes. In Rails all queries will show with params placeholders `?` and the actual expensive query might only trigger on a specific set of params.

On that same note it could be cool if we could also get some kind of `EXPLAIN` output as well. Raw explain output would help me not have to go back and forth between two tools (scout & the database CLI). Bonus points if you have some kind of visualization. I've not played with it but this looks promising http://tatiyants.com/postgres-query-plan-visualization/.

**Comment by itsderek23** [comment]
> I'd love to see support for SQL Server (direct db adapter: https://github.com/rails-sqlserver/tiny_tds) as well! Any chance of adding that, or providing instructions on how to add a new database for PR purposes?

It's likely we'll provide the fundamentals for most db systems (it's basically pivoting our data on the metric type vs. a web endpoint or background job). Additional metrics (like cache hit rates) that are db-specific would likely be added based on db popularity. 

> When showing slow queries it would be helpful to show an example of what inputs that query takes. In Rails all queries will show with params placeholders ? and the actual expensive query might only trigger on a specific set of params.

Yes - that's a pet peeve of @dlanderson :). 

I think it's mostly a security question: VividCortex, for example, [does collect raw queries](https://docs.vividcortex.com/general-reference/security/#data-sent-to-vividcortex) but encrypts the queries before writing to their DB.

New Relic defaults to obfuscated queries, but you can optionally capture queries in raw form ([docs](https://docs.newrelic.com/docs/apm/transactions/transaction-traces/security-options-transaction-traces)).

> On that same note it could be cool if we could also get some kind of EXPLAIN output as well. Raw explain output would help me not have to go back and forth between two tools (scout & the database CLI).

Yes. One challenge w/the Heroku Expensive queries and [pg_stat_statements](https://www.postgresql.org/docs/current/static/pgstatstatements.html) is that the queries are obfuscated: you need a raw query to run an explain.

Auto-running `EXPLAIN` on a repeated slow query would be pretty helpful. We'd want to avoid using `EXPLAIN ANALYZE`:

> Important: Keep in mind that the statement is actually executed when the ANALYZE option is used. Although EXPLAIN will discard any output that a SELECT would return, other side effects of the statement will happen as usual. If you wish to use EXPLAIN ANALYZE on an INSERT, UPDATE, DELETE, CREATE TABLE AS, or EXECUTE statement without letting the command affect your data, use this approach:

> Bonus points if you have some kind of visualization. I've not played with it but this looks promising http://tatiyants.com/postgres-query-plan-visualization/.

Yes - that's a beautiful tool. The Postgres `EXPLAIN` output can be a quite a bit to digest.

Related: [Dexter](https://github.com/ankane/dexter) is pretty fascinating. Just being able to suggest to the user to create an index based on measuring potential performance would be an incredible time-saver. I haven't ran this against a database yet - would be interested to hear from folks that have.

**Comment by itsderek23** [comment]
Completed: http://blog.scoutapp.com/articles/2017/11/04/scout-database-monitoring
