### ISSUE TITLE
teams/groups

### ISSUE THREAD

**Issue by matthewford** [scoutapp/roadmap#81]
Hello, 

We use Sentry.io and I do like their permission system, where you can have teams which contain a group of apps, and then you can assign people to teams, this would let us share data with specific people without sharing data on other apps.

**Comment by geomic** [comment]
It would be terrific if ScoutAPM added this. In our case, even a function similar to airbrake that literally just allows you to define which apps any of your team members have full access to, would suffice.

**Comment by matthewchigira** [comment]
+1 for Commutatus

They would like to be able to give permissions per-app

**Comment by geomic** [comment]
@matthewford was this closed because it was done, or because it won’t be done? Let us know so we can plan alternatives if need be.

**Comment by matthewford** [comment]
It was closed as I no longer use scout.
