### ISSUE TITLE
scale overview graph correctly when a data segment is disabled

### ISSUE THREAD

**Issue by aleksclark** [scoutapp/roadmap#89]
The overview graph doesn't currently scale properly when a data segment is disabled:
![2019-08-27-072718_1114x284_scrot](https://user-images.githubusercontent.com/607132/63771146-31f36980-c89c-11e9-9313-964ce8998a47.png)
![2019-08-27-072728_965x306_scrot](https://user-images.githubusercontent.com/607132/63771148-31f36980-c89c-11e9-86a3-47f4ab7d60c3.png)

**Comment by dlanderson** [comment]
Thanks @aleksclark - This looks like a regression of the same issue earlier in the year. We're looking into it.
