### ISSUE TITLE
PHP Database Monitoring

### ISSUE THREAD

**Issue by iredmedia** [scoutapp/roadmap#93]
Wondering when Database addon will be available for PHP - I think this is the last feature keeping me on NewRelic (Amazing work team, beautiful interface, a breeze to setup, love the product you've built)

"The database addon does not yet support Php."

**Comment by dlanderson** [comment]
Hi @iredmedia - thanks! The DB addon is now enabled. Install the latest scout-apm-php and you should be good to go!
